-- SQL script to set up the expenses and income tables in Supabase

-- Create the expenses table
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DECIMAL(12, 2) NOT NULL CHECK (amount > 0),
    category TEXT NOT NULL,
    description TEXT,
    date TIMESTAMPTZ DEFAULT NOW(),
    type TEXT DEFAULT 'expense'  -- Optional: mostly redundant now but good for clarity
);

-- Create the income table
CREATE TABLE IF NOT EXISTS income (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DECIMAL(12, 2) NOT NULL CHECK (amount > 0),
    source TEXT NOT NULL,       -- Stored as 'description' in Transaction model usually, but let's keep it aligned
    description TEXT,
    date TIMESTAMPTZ DEFAULT NOW(),
    category TEXT DEFAULT 'income', -- Optional: constant for income
    type TEXT DEFAULT 'income'
);

-- Create the budgets table (AI budget, one row per monthly period)
CREATE TABLE IF NOT EXISTS budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period TEXT NOT NULL,              -- monthly label, e.g. '2026-09'
    monthly_income DECIMAL(12, 2) NOT NULL DEFAULT 0,
    allocations JSONB NOT NULL DEFAULT '{}',  -- category -> planned amount
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (period)
);

-- Note: In Supabase, you can run this in the SQL Editor.
